---
title: "401 HW8"
author: "Sylvia"
date: "10/29/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

(a)
```{r}
Brain.data <- read.csv("Brain.csv", header = T)

pairs(~Brain+Body+Gest+Litter, data = Brain.data, lower.panel = NULL)
```

(b)
```{r}
pairs(~log(Brain)+log(Body)+log(Gest)+log(Litter), data = Brain.data, lower.panel = NULL)
```

(c)

```{r}
model1 <- lm(log(Brain)~log(Litter), data = Brain.data)
e.hat.md1 <- resid(model1)
plot(log(Brain.data$Body), e.hat.md1, xlab = "log(Body)", ylab = "Resid of model 1", main = "Resid(model1) vs log(Body)")
abline(h = 0,lty = 1)
lines(lowess(e.hat.md1~log(Brain.data$Body), f = 8/10, iter = 3), lty = 5)

plot(log(Brain.data$Gest), e.hat.md1, xlab = "log(Gest)", ylab = "Resid of model 1", main = "Resid(model1) vs log(Gest)")
abline(h = 0,lty = 1)
lines(lowess(e.hat.md1~log(Brain.data$Gest), f = 8/10, iter = 3), lty = 5)
```

```{r}
model.full <- lm(log(Brain)~log(Body)+log(Gest)+log(Litter), data = Brain.data)
par(mfrow = c(2,2))

y.hat.log <- fitted(model.full)
ep.hat.log <- resid(model.full)
plot(y.hat.log, ep.hat.log, main = "Residual Plot", ylab = "Residuals", xlab = "y-hat")
abline(h=0, lty = 1)
lines(lowess(ep.hat.log~y.hat.log, f = 8/10, iter = 3), lty = 5)

plot(log(Brain.data$Brain), y.hat.log, main = "y-hat vs y", xlab = "log(Brain)", ylab = "y-hat")
boxplot(ep.hat.log)
qqnorm(ep.hat.log)

summary(model.full)
```

```{r}
head(sort(ep.hat.log, decreasing = TRUE), 2)
Brain.data[c(24, 52),]
```

```{r}
confint(model.full, level = 0.95)
```

```{r}
anova(model.full)
```

```{r}
model.reduced <- lm(log(Brain)~log(Body), data = Brain.data)
anova(model.reduced)
1-pf(23.665, 2, 92)
```
